version: '3'
services:
    web:
        image: nginx:latest
        ports: 
            - "8080:80"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./:/app
    php:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: 'secret'
            MYSQL_USER: 'nasoma_user'
            MYSQL_PASSWORD: 'secret'
            MYSQL_DATABASE: 'nasoma_schema'
        # volumes:
            # - ./mysqldata:/var/lib/mysql
        # ports:
            # - 4406:3306
volumes:
    mysqldata: {}